import React from 'react'

const Home = () => {
  return (
    <div className='bg-red-600'>
        <div>
            HOME
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
        <div>
            home
        </div>
    </div>
  )
}

export default Home